### ISSUE TITLE
Build with maven under java 16

### ISSUE THREAD

**Issue by TTRCharlie** [KoxSosen/Ducky#10]
I believe the maven can't works under Java 16, however I don't know why
![image](https://user-images.githubusercontent.com/41184885/119459091-ab541080-bd3d-11eb-9f4f-1040f2e3693d.png)

 But, if I build your code under Java 11, I got this error message.
 
![image](https://user-images.githubusercontent.com/41184885/119459256-cfafed00-bd3d-11eb-8ae5-dec7da55ca0e.png)

**Comment by KoxSosen** [comment]
I updated the project to only work with java 16 or newer. Due to this change I can finally compile the jar with your pr. To "disable" the maven restriction, please edit the `pom.xml` file, line 99 and 100. You can change the compiler target version there.

**Comment by TTRCharlie** [comment]
Ok, thanks for the help
