### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by TTRCharlie** [KoxSosen/Ducky#14]
When I tried to build this with gradlew script under Ubuntu 18.04 under Windows subsystem of Linux
I have got this message
```
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain
```
After a Google search I tried to install a gradle, and run gradle warpper, and I got thiss message

```
* Where:
Build file '/mnt/c/Users/tcmba/Desktop/Ducky/build.gradle' line: 11

* What went wrong:
A problem occurred evaluating root project 'Ducky'.
> Could not find method application() for arguments [build_avvyldzcp5iz84edo7523mfty$_run_closure1@12b5b73b] on root project 'Ducky' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

Java version: OpenJDK 11 JDK
Gradle version: 4.4.1

**Comment by TTRCharlie** [comment]
Now, I guess I fixed it, and if its works correctly, I will make a pull request

**Comment by KoxSosen** [comment]
Oh hello! 

**Don't build ducky directly.** I do not provide support for self hosting tho, but building Ducky directly isn't something you should do. There is a different method for building the bot.

**Comment by TTRCharlie** [comment]
Ok
